# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-1043   # Optional: build with a specific pipeline version

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    # failOnThreshold: moderate
    variableGroupName: ffc-pay-request-editor-env-var
    pr_params:
      processingActive: ${{ eq(variables['pr_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['pr_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(pr_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(pr_azureAppRegistrationTenantId)
    snd2_params:
      processingActive: ${{ eq(variables['snd2_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['snd2_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(snd2_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(snd2_azureAppRegistrationTenantId)
    dev_params:
      processingActive: ${{ eq(variables['dev_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['dev_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(dev_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(dev_azureAppRegistrationTenantId)
    test_params:
      processingActive: ${{ eq(variables['test_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['test_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(test_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(test_azureAppRegistrationTenantId)
    pre_params:
      processingActive: ${{ eq(variables['pre_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['pre_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(pre_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(pre_azureAppRegistrationTenantId)
    prd_params:
      processingActive: ${{ eq(variables['prd_processingActive'], 'true') }}
      azureAppRegistrationEnabled: ${{ eq(variables['prod_azureAppRegistrationEnabled'], 'true') }}
      azureAppRegistrationClientId: $(prd_azureAppRegistrationClientId)
      azureAppRegistrationTenantId: $(prd_azureAppRegistrationTenantId)
