# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-request-editor:
    build:
      target: development
    image: ffc-pay-request-editor-development
    container_name: ffc-pay-request-editor-development
    ports:
      - "3001:3001"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-request-editor-postgres:
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
