version: '3.8'

services:
  ffc-pay-request-editor:
    build:
      context: .
      target: production
    image: ffc-pay-request-editor
    container_name: ffc-pay-request-editor
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-request-editor-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
