{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-request-editor.container-secret") -}}
{{- define "ffc-pay-request-editor.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  {{- if .Values.azureAppRegistration.enabled }}
  AZUREID_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AZUREID_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
{{- end -}}
