{{- include "ffc-helm-library.azure-ingress" (list . "ffc-pay-request-editor.ingress") -}}
{{- define "ffc-pay-request-editor.ingress" -}}
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
    nginx.org/client-max-body-size: "4m"
{{- end -}}
