environment: development
environmentCode:
name: ffc-pay-request-editor
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-request-editor

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-request-editor-config-map

containerSecret:
  name: ffc-pay-request-editor-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 120Mi
  requestCpu: 40m
  limitMemory: 1000Mi
  limitCpu: 500m
  port: 3001
  messageQueueHost: namespace.servicebus.windows.net
  debtTopicAddress: ffc-pay-debt-data
  debtSubscriptionAddress: ffc-pay-request-editor
  manualLedgerTopicAddress: ffc-pay-manual-check-data
  manualLedgerSubscriptionAddress: ffc-pay-request-editor
  qcTopicAddress: ffc-pay-quality-check
  eventTopicAddress: ffc-pay-event
  eventsTopicAddress: ffc-pay-events
  debtResponseTopicAddress: ffc-pay-debt-data-response
  cookiePassword: cookiecookiecookiecookiecookiecookie
  useV2Events: true
  processingActive: true
  
livenessProbe:
  path: /healthz
  port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

postgresService:
  postgresDb: ffc_pay_request_editor
  postgresqlHost: ffc-pay-request-editor-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

ingress:
  class: nginx
  endpoint: ffc-pay-request-editor
  server: example.com

service:
  port: 80
  type: ClusterIP

azureAppRegistration:
  enabled: true
  clientId:
  clientSecret:
  tenantId:
  redirectUrl: authenticate
