environment: development
name: ffc-pay-request-editor
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-request-editor

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-request-editor-config-map

containerSecret:
  name: ffc-pay-request-editor-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
