---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  debtTopicAddress: ffc-pay-debt-data-prd
  debtSubscriptionAddress: ffc-pay-request-editor
  manualLedgerTopicAddress: ffc-pay-manual-check-data-prd
  manualLedgerSubscriptionAddress: ffc-pay-request-editor
  qcTopicAddress: ffc-pay-quality-check-prd
  eventsTopicAddress: ffc-pay-events-prd
  debtResponseTopicAddress: ffc-pay-debt-data-response-prd
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: prd-ffc-pay-cookie-password
        objectType: secret
      - objectName: prd-ffcPayRequestEditorClientSecret
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-request-editor
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-ffc-pay-cookie-password
          key: COOKIE_PASSWORD
        - objectName: prd-ffcPayRequestEditorClientSecret
          key: AZUREID_CLIENT_SECRET